### ISSUE TITLE
class only protocols

### ISSUE THREAD

**Issue by davidkraus** [outfoxx/swiftpoet#1]
Hey, just tried to generate a class only protocol:

`protocol Test: class { ... }`

but i think this is not supported (correct me if i'm wrong) since swiftpoet treats the `class` keyword as a reserved keyword.

If you wan't i can put a PR together to fix this - Some thoughts:
We could just remove `class` from the reserved keywords and it would be possible but i first wanted to check with you if there would be a more elegant way to do it. 
Another thought i had was to add a `val unsafe: Boolean` to the `DeclaredTypeName` constructor to skip the keyword check. 

What do you think?

**Comment by davidkraus** [comment]
Ok found out that `protocol Test: class { ... }` and `protocol Test: AnyObject { ... }` are basically the same thing and that the first one might get deprecated in the future.

**Comment by kdubb** [comment]
Apologies, I had thought I responded to your issue. Thanks for updating with new syntax.
