### ISSUE TITLE
Preprocessor support

### ISSUE THREAD

**Issue by JakeWharton** [outfoxx/swiftpoet#10]
This is probably an insane feature to support fully, but perhaps we can distill targeted usage.

My sole use case is wrapping an entire `extension` like:
```swift
#if !FEATURE
extension Foo : Bar {}
#endif
```

**Comment by JakeWharton** [comment]
Maybe it's a property for all specs? Type, extension, property, function, etc. each can specify enclosing preprocessor directives? Honestly I don't know much about these to have a good recommendation... I'm just trying to satisfy a requirement.

**Comment by kdubb** [comment]
I'm assuming that most preprocessor code can be generated with `CodeBlock` since Swift requires all preprocessor code to be valid Swift code as well.

Adding the ability to guard imports & members was needed specifically because `FileSpec`s generate them from lists and that's what #23 adds
