### ISSUE TITLE
SwiftPoet 1.6.1 Update: Scope Issue in Nested Struct Generation

### ISSUE THREAD

**Issue by PaulWoitaschek** [outfoxx/swiftpoet#109]
With SwiftPoet 1.6.1, there seems to be an issue with nested scope resolution.

## Generating Code
```kotlin
FileSpec.builder("file")
  .addType(
    TypeSpec.structBuilder("A")
      .addFunction(
        FunctionSpec.constructorBuilder()
          .addParameter(
            ParameterSpec.builder(
              parameterName = "c",
              type = DeclaredTypeName.typeName("A.B.C"),
            ).build(),
          )
          .build(),
      )
      .addType(
        TypeSpec.structBuilder("B")
          .addType(
            TypeSpec.structBuilder("C")
              .build(),
          )
          .build(),
      )
      .build(),
  )
  .build()
```

 ## Output of 1.6.1

This does not compile, as the c: C is not in the scope of A.

```swift
import A

struct A {

  init(c: C) {
  }

  struct B {

    struct C {
    }

  }

}
```

## Output of 1.6.0

This successfully compiles

```swift
struct A {

  init(c: B.C) {
  }

  struct B {

    struct C {
    }

  }

}
```

## Diff
```patch
0a1,2
> import A
>
3c5
<   init(c: B.C) {
---
>   init(c: C) {
```

**Comment by PaulWoitaschek** [comment]
This can be worked around by qualifying:
```kotlin
DeclaredTypeName.typeName("A.B.C", alwaysQualify = true)
```

I would recommend to remove the `alwaysQualify` parameter and make it true by default. Generated code should mostly be correct.
Also see the discussion in https://github.com/outfoxx/swiftpoet/issues/52

**Comment by kdubb** [comment]
@PaulWoitaschek Thanks for the filing the issue. WRT `alwaysQualify` as stated in the discussion referenced we are not removing it; we will fix the issues and add test coverage for them.

**Comment by PaulWoitaschek** [comment]
From my understanding it's not possible to fix it. With swifts ambiguous importing system you will always have a clash if something already exists with the same name in a project. 

The only way to generate truly correct code is to overcome that umbiguity of swift by generating very explicit code. 

Just like in kotlinpoet you don't generate a wildcard import but instead are very specific about your imports.
