### ISSUE TITLE
Do not indent switch when used in beginControlFlow

### ISSUE THREAD

**Issue by JakeWharton** [outfoxx/swiftpoet#11]
If the string starts with `"switch "` then do not automatically indent. Downside: we would have to maintain a boolean stack of calls to `beginControlFlow` such that on symmetric calls to `nextControlFlow`/`endControlFlow` know whether or not to unindent. As a result, this may not be worth doing! And that's fine.

This syntactical formatting oddity offends me, but apparently it's idiomatic. I just ported all my use of `beginControlFlow` for `switch` to `addCode`. I'm perfectly fine leaving it like that, but figured I'd file and see what others thought.

**Comment by kdubb** [comment]
Why not add a `beginSwitch`/`endSwitch` pair? 

Alternatively we can make the control statement explicit in `beginControlFlow`/`endControlFlow`.

For example...
```kotlin
codeBlock.beginControlFlow("switch", code);
// generate cases
codeBlock.endControlFlow("switch")
```

In either case, I'm assuming you probably know your ending a switch when calling `endControlFlow` and `nextControlFlow` is irrelevant for `switch`.

**Comment by kdubb** [comment]
The second option (adding an explicit control statement name) essentially just pushes the idea of keeping a state stack onto the caller, which seems like a good idea since the calling code is probably structured in that way already,
