### ISSUE TITLE
How to indicate that a function returns "some TypeName"?

### ISSUE THREAD

**Issue by Lavmee** [outfoxx/swiftpoet#114]
I need to generate functions of this type:
```swift
public func onChange() -> some View {
}
```

**Comment by kdubb** [comment]
We will need to add some method of adding qualifiers to types (e.g. `some` and `any`).

**Comment by Lavmee** [comment]
Is it possible to use some kind of workaround?

**Comment by kdubb** [comment]
Without using `CodeWriter` to write the signature manually. I opened PR #115... should be in fairly quickly.
