### ISSUE TITLE
Rename KDoc & JavaDoc to whatever is appropriate

### ISSUE THREAD

**Issue by JakeWharton** [outfoxx/swiftpoet#13]
I don't know what Swift calls it, but I _suspect_ it's not KDoc 😀

**Comment by kdubb** [comment]
I've looked and Swift's documentation refers to it as Markdown.  So, I guess `MarkDoc`?  Otherwise we can just generically refer to it as `Doc`.

**Comment by kdubb** [comment]
Also, `KDoc` isn't the only offender, there are numerous references to `JavaDoc` as well 🙄
