### ISSUE TITLE
Publish GitHub releases

### ISSUE THREAD

**Issue by LouisCAD** [outfoxx/swiftpoet#28]
Useful for those of us who click "Watch" then "Releases only" in the GitHub UI to follow new releases.

**Comment by kdubb** [comment]
It certainly looks like the project has releases to me 🤔

We are actively working on the codebase and their are recent commits that contain API breaking changes. A new `1.0.0` release will be published when they are done (very soon!).

Thanks for interest in the project!

**Comment by LouisCAD** [comment]
I think I've been confused because [the latest GitHub release](https://github.com/outfoxx/swiftpoet/releases/tag/v0.3.0) is older than the latest version published on Maven Central according to commits and the badge in the README.

About the project, I'm wondering what people are and will use it for!

**Comment by kdubb** [comment]
Yes, the latest "SNAPSHOT" is the working version and is updated as changes are committed; it's not a stable release.

**Comment by LouisCAD** [comment]
There's also a 0.3.1

**Comment by kdubb** [comment]
Yes, that's the latest stable release. This is a ubiquitous Maven Repository publishing paradigm.
