### ISSUE TITLE
No ways to create @escaping lambda at all

### ISSUE THREAD

**Issue by Alex009** [outfoxx/swiftpoet#44]
To create lambda type i use `FunctionTypeName.get` but in all variants i can't pass `escaping = true` and as i see in sources - here no ways to change value after creation and also we can't use constructor from outside. so `@escaping` lamda can't be created, but logic for write this lambda - already done. need to add some way to change/set `escaping` flag

**Comment by mathaeus** [comment]
@Alex009 maybe you can help me answer a similar question. I'm looking into how to set `@escaping` for function parameters. I'm using `ParameterSpec`, and I guess a similar feature is missing there... or how would you solve this? 🤔 
A `FunctionTypeName` is not suitable there from what I can see.

**Comment by Alex009** [comment]
hi @mathaeus . i fork this project and add required logic, here pr - https://github.com/outfoxx/swiftpoet/pull/45
and for now i use library from jitpack
https://github.com/icerockdev/moko-kswift/blob/master/gradle/libs.versions.toml#L34
to create escaping param i call `makeEscaping`:
https://github.com/icerockdev/moko-kswift/blob/master/kswift-gradle-plugin/src/main/kotlin/dev/icerock/moko/kswift/plugin/KmTypeExt.kt#L44

**Comment by mathaeus** [comment]
Thanks @Alex009! I tried it out with your fork, and that also works for me.

@JakeWharton @kdubb @efirestone is there any chance this could get merged to the main repo and create a new release? :)
That would be much appreciated 🙇‍♂️
