### ISSUE TITLE
Is there a way to add 'weak' modifier to a property?

### ISSUE THREAD

**Issue by rjuszczyk** [outfoxx/swiftpoet#58]
Is there a way to add 'weak' modifier to a property?

**Comment by kdubb** [comment]
There is not. This needs to be added.

**Comment by kdubb** [comment]
@rjuszczyk Two new modifiers were added, `WEAK` and `UNOWNED` that can be used on _mutable_ `PropertySpec`s.

For example:
```
val property = PropertySpec.varBuilder("test", STRING, UNOWNED)
```
