### ISSUE TITLE
Missing support for generate implicitly unwrapped optionals

### ISSUE THREAD

**Issue by devslashwill** [outfoxx/swiftpoet#59]
There doesn't seem to be a way to generate implicitly unwrapped optionals. It probably wouldn't fit too cleanly with the ParameterizedTypeName abstraction as it only applies to Optional types.

**Comment by kdubb** [comment]
@devslashwill `TypeName` now has two new methods `makeImplicit` and `makeNonImplicit` which work similarly to the optional framework.
