### ISSUE TITLE
1.4.0 Release

### ISSUE THREAD

**Issue by francybiga** [outfoxx/swiftpoet#62]
Hi, while using swiftpoet 1.3.1 we stumbled upon the problem with public modifier on top level members, but we noticed it has already been fixed in #57. 

Is there a chance that a 1.4.0 version will be released soon? 

We would prefer to avoid forking  for the only for producing our own artefacts and also we cannot check-in snapshot versions in our project.  Thank you.

**Comment by kdubb** [comment]
@francybiga Done!
