### ISSUE TITLE
Support Subscript builders

### ISSUE THREAD

**Issue by lickel** [outfoxx/swiftpoet#69]
I wanted to add conformance to `@dynamicMemberLookup` in some generated code.
This is not possible as there's no way (that I can tell) to create subscripts.

Specifically, I wanted to create something like `subscript<Property>(dynamicMember keyPath: KeyPath<BackingData, Property>) -> Property`.

There doesn't seem to be any "escape hatch" for [TypeSpec.Builder](https://outfoxx.github.io/swiftpoet/1.0.0/swiftpoet/io.outfoxx.swiftpoet/-type-spec/-builder/index.html) to just type "raw" Swift code.
As such, I think the only way to solve this would be a dedicated function/builder.

**Comment by kdubb** [comment]
What's wrong with creating a function named `subscript`?

**Comment by lickel** [comment]
There's two problems: 
* I need to support both the getter and setter flavors
* the FunctionSpec builder notices it's a keyword and escapes it

**Comment by kdubb** [comment]
Got it. I tend to forget that subscript is kind of a special property.

That being the case... adding support to `PropertySpec` should be easy.

**Comment by lickel** [comment]
Yeah I figured it should be relatively straightforward since it's basically a special property except that it shares the flexibile generics and method signatures of a function.
