### ISSUE TITLE
Why ComposedTypeName.composed is internal?

### ISSUE THREAD

**Issue by comm1x** [outfoxx/swiftpoet#71]
All constructors of ComposedTypeName are internal, so I can't make a union of types.
How to make union?

Version: 1.4.3

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2980388/231573666-5fc5caf8-a2cb-4dfa-9b1f-d6a6d9fcfe16.png">

**Comment by kdubb** [comment]
Apparently this is just a mistake.
