### ISSUE TITLE
Including sub types within external extensions do not emit imports

### ISSUE THREAD

**Issue by dnkoutso** [outfoxx/swiftpoet#88]
Given test:

```kotlin
@Test
  @DisplayName("Generates correct imports for extension types ")
  fun testParentExtensionBug() {
    val parentElement = typeName(".Parent")
    val obsElement = typeName("RxSwift.Observable.Element")

    val extension =
      ExtensionSpec.builder(parentElement) // <----- using parentElement vs obsElement.enclosingTypeName()!! fails.
        .addFunction(
          FunctionSpec.builder("test")
            .returns(obsElement)
            .build()
        )
        .build()

    val testFile = FileSpec.builder("Test", "Test")
      .addExtension(extension)
      .build()

    val out = StringWriter()
    testFile.writeTo(out)

    assertThat(
      out.toString(),
      equalTo(
        """
            import RxSwift // <------ this is missing but should be there.

            extension Parent {

              func test() -> RxSwift.Observable.Element { // <---- this looks right if its fully qualified imo?
              }

            }

        """.trimIndent()
      )
    )
  }
```

Branch: https://github.com/outfoxx/swiftpoet/compare/extension_import_bug?expand=1

Seems related to https://github.com/outfoxx/swiftpoet/pull/55 

It seems when using `obsElement` as the extension type imports are emitted correctly which is why the test that was added in #55 passes correctly.

When removing:

```kotlin
if (typeSpec is ExternalTypeSpec) {
  return stackTypeName(i, simpleName)
}
```

Things start working, perhaps this is meant to check an additional condition? I am still getting familiarized with this code @kdubb 

cc @lickel

**Comment by dnkoutso** [comment]
@kdubb any ideas would be greatly appreciated, or hints...

**Comment by dnkoutso** [comment]
Seems somehow that `resolve` returns back a type in the failing test.

Notice resolved came back as `Parent.Element`

<img width="1840" alt="Screenshot 2023-11-06 at 2 20 11 PM" src="https://github.com/outfoxx/swiftpoet/assets/310370/9d4a164e-53d6-4e72-82a2-ae349e6b7b7c">

**Comment by kdubb** [comment]
@dnkoutso I'll have a look at this tonight

**Comment by dnkoutso** [comment]
Thanks @kdubb !

**Comment by dnkoutso** [comment]
@kdubb sorry for the additional ping, was hoping for any guidance on this. Currently it can cause an error in Wire output with a missing import.

Thanks again and apologies

**Comment by dnkoutso** [comment]
Would love an update here as this is currently blocking us.
